version: '3.1'
services: 
  fastapi:
    image: fastapi
    ports:
      - "80:80"

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - "8080:8080"  
