name: Build and Push

on:
  workflow_dispatch:
    inputs:
      environment:
        description: The environment to deploy to
        type: choice
        options:
          - dev
          - prod
        default: dev
        required: true
      app:
        description: "The name of the app"
        type: string
        default: ''
        required: true
jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:

    - run: |
        echo "It's working with ${{ github.event.inputs.app }}"